# Assignment-04 MD Rashadul Islam

In [1]:
import pandas as pd
import numpy as np #mathematical library

In [2]:
df = pd.read_csv('supershops.csv')

In [3]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [4]:
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()
df6 = df.copy()
df7 = df.copy()

1. Normalization
2. Standardization
3. Log Transformation
4. Robust Scaler
5. Max Absolute Scaler


# Normalization

In [5]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [6]:
from sklearn.preprocessing import MinMaxScaler
m = MinMaxScaler() #default feature_range=(0,1)

In [7]:
df_ms = m.fit(df[['Marketing Spend']]) # calculation everything

In [8]:
df_ms

MinMaxScaler()

In [9]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [10]:
df[['Marketing_Spend_New']] = m.transform(df[['Marketing Spend']])

In [11]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61       136897.80  471784.10    Dhaka  192261.83   
1        162597.70       151377.59  443898.53      Ctg  191792.06   
2        153441.51       101145.55  407934.54  Rangpur  191050.39   
3        144372.41       118671.85  383199.62    Dhaka  182901.99   
4        142107.34        91391.77  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

In [12]:
df[['Administration']] = m.fit_transform(df[['Administration']])
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

# Perform Normalization using loop

In [102]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

# Standardization

In [74]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

In [27]:
X = df.iloc[:, [0,4]]
Y = df.iloc[:, 3]

In [28]:
X.head()

Marketing Spend     Profit
0        114523.61  192261.83
1        162597.70  191792.06
2        153441.51  191050.39
3        144372.41  182901.99
4        142107.34  166187.94

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state = 40 )

In [31]:
X_train.head()

Marketing Spend     Profit
21         78389.47  111313.02
44         22177.74   65200.33
41         27892.92   77798.83
23         67532.53  108733.99
36         28663.76   90708.19

In [33]:
scaler = StandardScaler().fit(X_train)

In [34]:
print(scaler)

StandardScaler()


In [37]:
scaler.mean_

array([ 74393.67864865, 110624.5572973 ])

In [38]:
scaler.scale_

array([44910.78106948, 36481.51651982])

In [39]:
scaler.transform(X_train)

array([[ 0.08897176,  0.01887155],
       [-1.16265933, -1.24512991],
       [-1.03540303, -0.89979065],
       [-0.15277286, -0.05182261],
       [-1.01823922, -0.54593036],
       [ 1.27994259,  1.2709604 ],
       [ 0.39185939,  0.64917237],
       [-0.79791907, -0.81188503],
       [ 0.45119414,  0.40419955],
       [-1.31122076, -1.12017211],
       [ 0.05901325, -0.05681006],
       [ 1.55817222,  1.98120691],
       [-0.00888692, -0.00746425],
       [-1.01622255, -0.88770014],
       [ 0.02082332, -0.13406837],
       [-0.62273708, -0.38133714],
       [ 0.04141948,  0.215163  ],
       [-0.18574958, -0.20125746],
       [ 1.01422332,  0.6024446 ],
       [ 2.02524915,  0.52882897],
       [-0.27608513, -0.29294197],
       [ 1.02756711,  1.13995296],
       [-1.62718654, -1.67574742],
       [-0.24459202, -0.36173708],
       [ 1.08974282,  1.07274605],
       [-1.64440758, -2.05449648],
       [-1.1300794 , -1.07249015],
       [ 0.61275713,  0.97302404],
       [-0.2951919 ,

In [40]:
X_train_scaled = scaler.transform(X_train)

In [41]:
print(X_train_scaled)

[[ 0.08897176  0.01887155]
 [-1.16265933 -1.24512991]
 [-1.03540303 -0.89979065]
 [-0.15277286 -0.05182261]
 [-1.01823922 -0.54593036]
 [ 1.27994259  1.2709604 ]
 [ 0.39185939  0.64917237]
 [-0.79791907 -0.81188503]
 [ 0.45119414  0.40419955]
 [-1.31122076 -1.12017211]
 [ 0.05901325 -0.05681006]
 [ 1.55817222  1.98120691]
 [-0.00888692 -0.00746425]
 [-1.01622255 -0.88770014]
 [ 0.02082332 -0.13406837]
 [-0.62273708 -0.38133714]
 [ 0.04141948  0.215163  ]
 [-0.18574958 -0.20125746]
 [ 1.01422332  0.6024446 ]
 [ 2.02524915  0.52882897]
 [-0.27608513 -0.29294197]
 [ 1.02756711  1.13995296]
 [-1.62718654 -1.67574742]
 [-0.24459202 -0.36173708]
 [ 1.08974282  1.07274605]
 [-1.64440758 -2.05449648]
 [-1.1300794  -1.07249015]
 [ 0.61275713  0.97302404]
 [-0.2951919  -0.36020973]
 [ 0.26777582  0.33310849]
 [-1.65647706 -1.86573459]
 [ 0.43352778  0.84867532]
 [ 1.96398324  2.22489388]
 [-0.67519932 -0.56673678]
 [ 1.24478911  1.23701115]
 [-0.05090267 -0.15394775]
 [ 1.34092037  1.24715081]]


In [42]:
print(X_train_scaled.mean(axis=0))

[-6.60132609e-17 -1.62032550e-16]


In [44]:
print(X_train_scaled.std(axis=0))

[1. 1.]


In [47]:
X_test.head()

Marketing Spend     Profit
33         55493.95   96778.92
29         65605.48  101004.64
49             0.00   14681.40
38         20229.59   81229.06
45          1000.23   64926.08

In [45]:
scaler = StandardScaler().fit(X_test)

In [46]:
scaler.mean_

array([ 71808.82076923, 115963.33384615])

In [48]:
scaler.scale_

array([46864.26302872, 48108.28119133])

In [49]:
scaler.transform (X_test)

array([[-0.34813032, -0.39877571],
       [-0.13236826, -0.31093802],
       [-1.53227249, -2.10529105],
       [-1.10060902, -0.72200197],
       [-1.51092936, -1.06088292],
       [ 0.91145761,  1.58597427],
       [ 0.42549136,  0.1726016 ],
       [ 1.50004534,  1.04399087],
       [ 0.61588804,  0.58817454],
       [ 1.74189636,  1.56079274],
       [ 0.13238849,  0.22926606],
       [-0.55041516, -0.40499938],
       [-0.15244261, -0.17791103]])

In [55]:
X_test_scaled = scaler.transform(X_test)

In [56]:
print(X_test_scaled)

[[-0.34813032 -0.39877571]
 [-0.13236826 -0.31093802]
 [-1.53227249 -2.10529105]
 [-1.10060902 -0.72200197]
 [-1.51092936 -1.06088292]
 [ 0.91145761  1.58597427]
 [ 0.42549136  0.1726016 ]
 [ 1.50004534  1.04399087]
 [ 0.61588804  0.58817454]
 [ 1.74189636  1.56079274]
 [ 0.13238849  0.22926606]
 [-0.55041516 -0.40499938]
 [-0.15244261 -0.17791103]]


In [57]:
print(X_test_scaled.mean(axis=0))

[ 1.34507790e-16 -1.81478764e-16]


In [58]:
print (X_test_scaled.std(axis=0))

[1. 1.]


# Log Transformation

In [18]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html

In [19]:
from sklearn.preprocessing import FunctionTransformer
ft = FunctionTransformer(np.log1p) #np.log1p will avoid 0

In [20]:
df2.head(2)

Marketing Spend  Administration  Transport   Area     Profit
0        114523.61       136897.80  471784.10  Dhaka  192261.83
1        162597.70       151377.59  443898.53    Ctg  191792.06

In [21]:
df2['Transport'] = ft.fit_transform(df2[['Transport']])

In [22]:
df2.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  13.064279    Dhaka  192261.83
1        162597.70       151377.59  13.003354      Ctg  191792.06
2        153441.51       101145.55  12.918864  Rangpur  191050.39
3        144372.41       118671.85  12.856314    Dhaka  182901.99
4        142107.34        91391.77  12.810851  Rangpur  166187.94

# Perform Log using loop

In [104]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

# Robust Scaler

In [59]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

In [ ]:
X = df.iloc[:, [0,4]]
Y = df.iloc[:, 3]

In [60]:
X.head()

Marketing Spend     Profit
0        114523.61  192261.83
1        162597.70  191792.06
2        153441.51  191050.39
3        144372.41  182901.99
4        142107.34  166187.94

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

In [62]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state = 50 )

In [63]:
X_train.head()

Marketing Spend     Profit
23         67532.53  108733.99
25         64664.71  107404.34
3         144372.41  182901.99
39         38558.51   81005.76
15        165349.20  129917.04

In [64]:
scaler = RobustScaler().fit(X_train)

In [65]:
print(scaler)

RobustScaler()


In [66]:
scaler.n_features_in_

2

In [67]:
scaler.transform(X_train)

array([[-0.06022595,  0.02102092],
       [-0.09797776,  0.        ],
       [ 0.95128961,  1.19357005],
       [-0.4416382 , -0.41734484],
       [ 1.22742681,  0.35591153],
       [-0.58203938, -0.46804437],
       [ 0.18840362,  0.24302981],
       [-0.9492201 , -1.46589097],
       [ 0.5583618 ,  1.34154319],
       [ 0.67435283,  0.66961554],
       [ 0.39235754,  0.6121009 ],
       [ 0.08269416,  0.06179376],
       [ 0.29684105,  0.28403156],
       [-0.9492201 , -1.02515223],
       [ 0.05458112,  0.17500479],
       [-0.57069983, -0.46107117],
       [-0.65727367, -0.66721868],
       [ 0.0424046 , -0.02641429],
       [ 0.        , -0.03787972],
       [-0.07972187, -0.06516558],
       [ 0.62970548,  0.39836933],
       [-0.74510361, -0.59514931],
       [ 0.76601663,  0.76435538],
       [-0.14442448, -0.15684125],
       [ 1.07067469,  1.32239109],
       [ 0.78679946,  0.7839356 ],
       [ 0.02483983,  0.04660459],
       [-0.63801232, -0.56764876],
       [-0.36908594,

In [68]:
X_train_scaled = scaler.transform(X_train)

In [69]:
print(X_train_scaled)

[[-0.06022595  0.02102092]
 [-0.09797776  0.        ]
 [ 0.95128961  1.19357005]
 [-0.4416382  -0.41734484]
 [ 1.22742681  0.35591153]
 [-0.58203938 -0.46804437]
 [ 0.18840362  0.24302981]
 [-0.9492201  -1.46589097]
 [ 0.5583618   1.34154319]
 [ 0.67435283  0.66961554]
 [ 0.39235754  0.6121009 ]
 [ 0.08269416  0.06179376]
 [ 0.29684105  0.28403156]
 [-0.9492201  -1.02515223]
 [ 0.05458112  0.17500479]
 [-0.57069983 -0.46107117]
 [-0.65727367 -0.66721868]
 [ 0.0424046  -0.02641429]
 [ 0.         -0.03787972]
 [-0.07972187 -0.06516558]
 [ 0.62970548  0.39836933]
 [-0.74510361 -0.59514931]
 [ 0.76601663  0.76435538]
 [-0.14442448 -0.15684125]
 [ 1.07067469  1.32239109]
 [ 0.78679946  0.7839356 ]
 [ 0.02483983  0.04660459]
 [-0.63801232 -0.56764876]
 [-0.36908594 -0.27595566]
 [ 0.8228497   0.77020342]
 [ 0.92147236  0.9293315 ]
 [-0.1331285  -0.11804459]
 [-0.21870109 -0.16798116]
 [-0.93605313 -0.6715544 ]
 [ 0.37601951  0.58265516]
 [-0.11450969 -0.15772215]
 [-0.94208459 -1.13402059]]


In [70]:
scaler =RobustScaler().fit(X_test)

In [71]:
scaler.transform(X_test)

array([[-0.66592052, -0.3129769 ],
       [-1.05223935, -0.4717121 ],
       [ 1.86073778,  2.20049625],
       [-1.23567712, -0.72229818],
       [ 0.94606464,  1.15416926],
       [ 0.0210773 ,  0.48749519],
       [-0.67488234, -0.31914405],
       [ 0.32511766,  0.68085595],
       [-0.24878068, -0.19951972],
       [ 0.        ,  0.        ],
       [ 0.31982756,  0.41543107],
       [-1.6470473 , -1.56131807],
       [ 0.36581854,  0.87325843]])

In [72]:
X_test_scaled = scaler.transform(X_test)

In [73]:
print(X_test_scaled)

[[-0.66592052 -0.3129769 ]
 [-1.05223935 -0.4717121 ]
 [ 1.86073778  2.20049625]
 [-1.23567712 -0.72229818]
 [ 0.94606464  1.15416926]
 [ 0.0210773   0.48749519]
 [-0.67488234 -0.31914405]
 [ 0.32511766  0.68085595]
 [-0.24878068 -0.19951972]
 [ 0.          0.        ]
 [ 0.31982756  0.41543107]
 [-1.6470473  -1.56131807]
 [ 0.36581854  0.87325843]]


# Max Absolute Scaler

In [75]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit  \
0        114523.61        0.651744  471784.10    Dhaka  192261.83   
1        162597.70        0.761972  443898.53      Ctg  191792.06   
2        153441.51        0.379579  407934.54  Rangpur  191050.39   
3        144372.41        0.512998  383199.62    Dhaka  182901.99   
4        142107.34        0.305328  366168.42  Rangpur  166187.94   

   Marketing_Spend_New  
0             0.692617  
1             0.983359  
2             0.927985  
3             0.873136  
4             0.859438

In [76]:
X = df.iloc[:, [0,4]]
Y = df.iloc[:, 3]

In [78]:
X.head()

Marketing Spend     Profit
0        114523.61  192261.83
1        162597.70  191792.06
2        153441.51  191050.39
3        144372.41  182901.99
4        142107.34  166187.94

In [79]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MaxAbsScaler

In [80]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state = 40 )

In [81]:
X_train.head()

Marketing Spend     Profit
21         78389.47  111313.02
44         22177.74   65200.33
41         27892.92   77798.83
23         67532.53  108733.99
36         28663.76   90708.19

In [82]:
scaler = MaxAbsScaler().fit(X_train)

In [83]:
print(scaler)

MaxAbsScaler()


In [84]:
scaler.max_abs_

array([165349.2 , 191792.06])

In [85]:
scaler.scale_

array([165349.2 , 191792.06])

In [86]:
X_train.describe()

Marketing Spend         Profit
count        37.000000      37.000000
mean      74393.678649  110624.557297
std       45530.269383   36984.733623
min           0.000000   35673.410000
25%       38558.510000   89949.140000
50%       73994.560000  108552.040000
75%      101913.080000  134307.350000
max      165349.200000  191792.060000

In [87]:
scaler.transform(X_train)

array([[0.47408436, 0.58038388],
       [0.13412668, 0.33995323],
       [0.16869099, 0.40564156],
       [0.40842369, 0.56693687],
       [0.17335288, 0.47295071],
       [0.797566  , 0.81854859],
       [0.55635219, 0.70027586],
       [0.23319442, 0.42236243],
       [0.57246821, 0.65367862],
       [0.09377566, 0.36372194],
       [0.46594728, 0.56598819],
       [0.87313643, 0.95364735],
       [0.4475048 , 0.57537444],
       [0.17390063, 0.40794134],
       [0.45557444, 0.55129258],
       [0.2807759 , 0.50425862],
       [0.46116861, 0.61772124],
       [0.39946683, 0.53851228],
       [0.72539353, 0.69138759],
       [1.        , 0.67738487],
       [0.37493063, 0.52107261],
       [0.72901786, 0.79362915],
       [0.00795565, 0.25804379],
       [0.38348453, 0.50798683],
       [0.74590551, 0.78084546],
       [0.00327821, 0.18600045],
       [0.14297577, 0.37279171],
       [0.61635061, 0.76187695],
       [0.36974101, 0.50827735],
       [0.52264964, 0.64015611],
       [0.

In [90]:
X_train_scaled = scaler.transform(X_train)

In [91]:
print (X_train_scaled)

[[0.47408436 0.58038388]
 [0.13412668 0.33995323]
 [0.16869099 0.40564156]
 [0.40842369 0.56693687]
 [0.17335288 0.47295071]
 [0.797566   0.81854859]
 [0.55635219 0.70027586]
 [0.23319442 0.42236243]
 [0.57246821 0.65367862]
 [0.09377566 0.36372194]
 [0.46594728 0.56598819]
 [0.87313643 0.95364735]
 [0.4475048  0.57537444]
 [0.17390063 0.40794134]
 [0.45557444 0.55129258]
 [0.2807759  0.50425862]
 [0.46116861 0.61772124]
 [0.39946683 0.53851228]
 [0.72539353 0.69138759]
 [1.         0.67738487]
 [0.37493063 0.52107261]
 [0.72901786 0.79362915]
 [0.00795565 0.25804379]
 [0.38348453 0.50798683]
 [0.74590551 0.78084546]
 [0.00327821 0.18600045]
 [0.14297577 0.37279171]
 [0.61635061 0.76187695]
 [0.36974101 0.50827735]
 [0.52264964 0.64015611]
 [0.         0.22190559]
 [0.56766982 0.7382241 ]
 [0.98335946 1.        ]
 [0.26652654 0.46899303]
 [0.7880179  0.81209097]
 [0.43609283 0.54751125]
 [0.81412828 0.81401967]]


In [92]:
scaler = MaxAbsScaler().fit(X_test)

In [93]:
print(scaler)

MaxAbsScaler()


In [94]:
scaler.max_abs_

array([153441.51, 192261.83])

In [95]:
scaler.scale_

array([153441.51, 192261.83])

In [96]:
X_test.describe()

Marketing Spend         Profit
count        13.000000      13.000000
mean      71808.820769  115963.333846
std       48777.871468   50072.686624
min           0.000000   14681.400000
25%       46014.020000   96479.510000
50%       65605.480000  107404.340000
75%      100671.960000  144259.400000
max      153441.510000  192261.830000

In [97]:
scaler.transform(X_test)

array([[0.36166191, 0.50337043],
       [0.42756018, 0.52534942],
       [0.        , 0.07636149],
       [0.1318391 , 0.42249187],
       [0.00651864, 0.33769615],
       [0.74636655, 1.        ],
       [0.59794224, 0.64634202],
       [0.92613361, 0.86438343],
       [0.65609339, 0.75032782],
       [1.        , 0.99369901],
       [0.50842246, 0.66052076],
       [0.29987987, 0.50181313],
       [0.42142905, 0.55863579]])

In [98]:
X_test_scaled = scaler.transform(X_test)

In [99]:
print(X_test_scaled)

[[-0.66592052 -0.3129769 ]
 [-1.05223935 -0.4717121 ]
 [ 1.86073778  2.20049625]
 [-1.23567712 -0.72229818]
 [ 0.94606464  1.15416926]
 [ 0.0210773   0.48749519]
 [-0.67488234 -0.31914405]
 [ 0.32511766  0.68085595]
 [-0.24878068 -0.19951972]
 [ 0.          0.        ]
 [ 0.31982756  0.41543107]
 [-1.6470473  -1.56131807]
 [ 0.36581854  0.87325843]]
